input_stream: "input_video"
output_stream: "output_video"
input_stream: "background_image"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:human_mask"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

node {
    calculator: "DemuxCalculator"
    input_stream: "throttled_input_video"
    output_stream: "OUTPUT:0:throttled_input_video_slimnet"
    output_stream: "OUTPUT:1:throttled_input_video_deeplab"
    output_stream: "SELECT:select"
    node_options: {
    [type.googleapis.com/mediapipe.DemuxCalculatorOptions] {
      output_data_stream_index: 0
    }
  }
}


node {
    calculator: "SlimnetSegmentationSubgraph"
    input_stream: "throttled_input_video_slimnet"
    output_stream: "human_mask_slimnet"
}

node {
    calculator: "DeeplabSegmentationSubgraph"
    input_stream: "throttled_input_video_deeplab"
    output_stream: "human_mask_deeplab"
}

node {
    calculator: "MuxCalculator"
    input_stream: "INPUT:0:human_mask_slimnet"
    input_stream: "INPUT:1:human_mask_deeplab"
    input_stream: "SELECT:select"
    output_stream: "OUTPUT:human_mask"
}

node {
  calculator: "MaskOverlayCalculator"
  input_stream: "VIDEO:1:throttled_input_video"
  input_stream: "VIDEO:0:background_image"
  input_stream: "MASK:human_mask"
  output_stream: "OUTPUT:output_video"
  node_options: {
    [type.googleapis.com/mediapipe.MaskOverlayCalculatorOptions] {
      mask_channel: ALPHA
    }
  }
}